# Generated by Django 3.1.3 on 2021-01-13 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_ad', models.IntegerField(null=True, verbose_name='Систолическое давление')),
                ('diastolic_ad', models.IntegerField(null=True, verbose_name='Диастолическое давление')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ад',
                'verbose_name_plural': 'Ад',
            },
        ),
    ]
